version: "2.4"

services:
  # chat-server:
  #   build: ./Chat-Server
  #   command: python -u app.py
  #   ports:
  #     - "5069:5000"
  #   environment:
  #     - DB_IP_ADDR=172.18.0.3
  #     - AUTH_IP_ADDR=172.18.0.4
  #   networks:
  #     app_net:
  #       ipv4_address: 172.18.0.2

  # db-chat:
  #   image: mongo:3-xenial
  #   networks:
  #     app_net:
  #       ipv4_address: 172.18.0.3

  authorization-server:
    build: ./Authorization-Server
    command: python -u authorization_server.py
    networks:
      app_net:
        ipv4_address: 172.18.0.4

  db-dataserver:
    build: ./Database
    environment:
      POSTGRES_DB: "bookalike"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
      app_net:
        ipv4_address: 172.18.0.5

  dataserver:
    build: ./Data-Server
    command: npm run start
    ports:
      - "5060:5000"
    environment:
      - AUTH_IP_ADDR=172.18.0.4
      - DS_DB_IP_ADDR=172.18.0.5
    networks:
      app_net:
        ipv4_address: 172.18.0.6

  webserver:
    build: ./Web-Server/backend
    volumes:
      - type: bind
        source: ./Web-Server/backend/
        target: /usr/src/app/
    command: npm run start
    ports:
      - "5150:5000"
    networks:
      app_net:
        ipv4_address: 172.18.0.7

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/28
          gateway: 172.18.0.1
